//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocoPM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChocoPM.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include All Versions.
        /// </summary>
        public static string HomeView_AvailablePackages_AllVersionCheckBox {
            get {
                return ResourceManager.GetString("HomeView_AvailablePackages_AllVersionCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Packages.
        /// </summary>
        public static string HomeView_AvailablePackages_Header {
            get {
                return ResourceManager.GetString("HomeView_AvailablePackages_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Word.
        /// </summary>
        public static string HomeView_AvailablePackages_MatchCheckBox {
            get {
                return ResourceManager.GetString("HomeView_AvailablePackages_MatchCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Prerelease.
        /// </summary>
        public static string HomeView_AvailablePackages_PrereleaseCheckBox {
            get {
                return ResourceManager.GetString("HomeView_AvailablePackages_PrereleaseCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Packages.
        /// </summary>
        public static string HomeView_InstalledPackages_Header {
            get {
                return ResourceManager.GetString("HomeView_InstalledPackages_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string HomeView_PackagesGrid_PageLabel {
            get {
                return ResourceManager.GetString("HomeView_PackagesGrid_PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string HomeView_PackagesGrid_PageOfLabel {
            get {
                return ResourceManager.GetString("HomeView_PackagesGrid_PageOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string HomeView_PackagesGrid_SearchLabel {
            get {
                return ResourceManager.GetString("HomeView_PackagesGrid_SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string HomeView_PackagesGrid_TitleColumnHeader {
            get {
                return ResourceManager.GetString("HomeView_PackagesGrid_TitleColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downloads.
        /// </summary>
        public static string HomeView_PackagesGrid_TotalDownloadsColumnHeader {
            get {
                return ResourceManager.GetString("HomeView_PackagesGrid_TotalDownloadsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string HomeView_PackagesGrid_VersionColumnHeader {
            get {
                return ResourceManager.GetString("HomeView_PackagesGrid_VersionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By:.
        /// </summary>
        public static string HomeView_PackageView_ByLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_ByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string HomeView_PackageView_CreatedLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_CreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:.
        /// </summary>
        public static string HomeView_PackageView_DependenciesLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_DependenciesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string HomeView_PackageView_DescriptionLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads:.
        /// </summary>
        public static string HomeView_PackageView_DownloadsLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_DownloadsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string HomeView_PackageView_GalleryUrlLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_GalleryUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated:.
        /// </summary>
        public static string HomeView_PackageView_LastUpdatedLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_LastUpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string HomeView_PackageView_LicenseUrlLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_LicenseUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Size (bytes):.
        /// </summary>
        public static string HomeView_PackageView_PackageSizeLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_PackageSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Site.
        /// </summary>
        public static string HomeView_PackageView_ProjectUrlLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_ProjectUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes:.
        /// </summary>
        public static string HomeView_PackageView_ReleaseNotesLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_ReleaseNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Abuse.
        /// </summary>
        public static string HomeView_PackageView_ReportAbuseUrlLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_ReportAbuseUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downloads:.
        /// </summary>
        public static string HomeView_PackageView_TotalDownloadsLabel {
            get {
                return ResourceManager.GetString("HomeView_PackageView_TotalDownloadsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeView_Title {
            get {
                return ResourceManager.GetString("HomeView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string InstallButton_Tooltip {
            get {
                return ResourceManager.GetString("InstallButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choco Package Manager.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string UninstallButton_Tooltip {
            get {
                return ResourceManager.GetString("UninstallButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateButton_Tooltip {
            get {
                return ResourceManager.GetString("UpdateButton_Tooltip", resourceCulture);
            }
        }
    }
}
